### PR TITLE
Windows: fix "IOError: [Errno 13] Permission denied" when re-opening named temporary file

### PR DESCRIPTION
**Pull request by anthrotype**
on Windows we need to close the temporary file, before we can re-open it by the name... Which basically makes the whole use of NamedTemporaryFile almost pointless...

See https://bugs.python.org/issue14243

Anyway, this fixes it for now.
If we find we need to do this often, we can wrap the `try... finally` in a custom @contextmanager that does the cleanup on exit.

### CODE REVIEW

**Comment by anthrotype** [comment]
rebased to fix the merge conflict.

**Comment by behdad** [comment]
Do we even need to write it to a temp file?  Why not keep in memory?

**Comment by anthrotype** [comment]
Maybe we don't. Feel free to close this and fix it in a different way. I'm off now.

**Comment by anthrotype** [comment]
actually we do need a temp file, as glyphsLib.build_masters expects a path.

**Comment by jamesgk** [comment]
Yea. We could add another function to the glyphsLib API which takes in the file contents instead; I'd be in favor of that since it would simplify things here.

**Comment by anthrotype** [comment]
ok, glyphsLib can now read from either a path or an open file-like object.
I updated this PR so that fontmake passes an io.StringIO to glyphsLib instead of a path to a temporary file.

If anyone could abort the first pending Travis build, it would be nice, as it's gonna fail anyway (as I updated the requirements.txt in the follow-up commit) and it takes ages.

**Pull request merged**
