### PR TITLE
Add option to run ttfautohint

### PR DESCRIPTION
**Pull request by jamesgk**

### CODE REVIEW

**Comment by dougfelt** [comment]
LGTM

**Comment by davelab6** [comment]
I have a trivia question :) Why in https://github.com/googlei18n/fontmake/blob/master/Lib/fontmake/ttfautohint.py#L34-L42 are the options underscore separated, instead of dash separated, then requiring the conversion of underscores to dashes?

**Comment by jamesgk** [comment]
That only applies to keyword arguments passed into the function in python, not to a string of command line arguments (where you should be able to use underscores or dashes). There's no way to pass keywords with dashes in python.

**Comment by anthrotype** [comment]
Because the hypen is not a valid character for Python variables.

**Comment by jamesgk** [comment]
Sorry, I was mistaken there, you can't use underscores when passing in a string of arguments. So kwargs have to have underscores, and a string of args has to have dashes.

**Comment by davelab6** [comment]
Got it! Thanks! :)

**Pull request merged**
