### PR TITLE
README.rst: integrate Dave's changes from PR #213

### PR DESCRIPTION
**Pull request by anthrotype**

### CODE REVIEW

**Comment by anthrotype** [comment]
Could anyone please take a look and see this makes sense?

I'd like to merge this and tag the first v1.1.0 release.

Thanks.

**Comment by anthrotype** [comment]
here's how this looks when formatted:
https://github.com/anthrotype/fontmake/blob/readme-rst/README.rst

**Comment by moyogo** [comment]
LGTM

**Comment by davelab6** [comment]
Thanks!!

On Dec 22, 2016 5:47 PM, "Cosimo Lupo" <notifications@github.com> wrote:

Merged #222 <https://github.com/googlei18n/fontmake/pull/222>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/fontmake/pull/222#event-903217988>, or mute
the thread

**Pull request merged**
